CREATE TABLE "log" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"timestamp"	TEXT NOT NULL,
	"date"	TEXT,
	"time"	TEXT,
	"uptime"	INTEGER,
	"internal_ip"	TEXT,
	"external_ip"	TEXT,
	"external_ipv6"	TEXT,
	"is_linked"	INTEGER,
	"is_connected"	INTEGER,
	"str_transmission_rate_up"	TEXT,
	"str_transmission_rate_down"	TEXT,
	"str_max_bit_rate_up"	TEXT,
	"str_max_bit_rate_down"	TEXT,
	"str_max_linked_bit_rate_up"	TEXT,
	"str_max_linked_bit_rate_down"	TEXT,
	"modelname"	TEXT,
	"system_version"	TEXT,
	"message"	TEXT
);